version: '3.2'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - bdd
      - redis
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - internalapp 
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    command: node dist/main

  redis:
    image: redis
    expose:
      - 6379
    networks:
      - internalapp
  
  bdd:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - 3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    networks:
      - internalapp

networks:
  internalapp:
    internal: true