version: '3.2'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
        - .env
    volumes:
      - .:/usr/src/app
    ports:
      - 4000:3000
    depends_on:
      - redis
      - bdd
    networks:
      - internalapp 
      - default

  redis: # Name of container
    image: redis
    expose:
      - 6379
    # ports:
    #   - '6379:6379'
    networks:
      - internalapp
  
  bdd:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - 3306
    # ports:
    #   - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    networks:
      - internalapp

networks:
  internalapp:
    internal: true